spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/coldchain_mvp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: coldchain_user
    password: coldchain_dev_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  datasource:
    mode: mysql
